---
- name: Jetson Nano Setup
  hosts: localhost
  connection: local 
  become: yes

  tasks:

  - name: update
    apt:
      update_cache: yes 
      force_apt_get: yes 
      cache_valid_time: 3600

  - name: Upgrade all apt packages
    apt: 
      state: latest 
      force_apt_get: yes

#  - shell: apt dist-upgrade -y
#
#  - shell: apt update -y

  - name: packages
    apt:
      state: present
      pkg:
      - nvidia-container
      - nvidia-jetpack
      - tmux 
      - ansible 
      - git 
      - vim

